"""add: monto exento para libros sat

Revision ID: 04e2a9159633
Revises: 9122ea0c8c51
Create Date: 2026-05-27 12:46:19.402611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import os

# revision identifiers, used by Alembic.
revision: str = '04e2a9159633'
down_revision: Union[str, None] = '9122ea0c8c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    tenant_schema = os.environ.get("TENANT_SCHEMA", "public")
    if tenant_schema == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat_libros_lineas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_exento', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    tenant_schema = os.environ.get("TENANT_SCHEMA", "public")
    if tenant_schema == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat_libros_lineas', schema=None) as batch_op:
        batch_op.drop_column('monto_exento')
    # ### end Alembic commands ###
