"""chg: agrega actividad_economica_id a empresa

Revision ID: 11dbf33816ed
Revises: da39e700b5e8
Create Date: 2026-05-28 14:14:18.410748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import os

# revision identifiers, used by Alembic.
revision: str = '11dbf33816ed'
down_revision: Union[str, None] = 'da39e700b5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    tenant_schema = os.environ.get("TENANT_SCHEMA", "public")
    if tenant_schema == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domicilios', schema=None) as batch_op:
        try:
            batch_op.drop_constraint('fk_domicilios_tipo_domicilio_id_tipos_domicilio', type_='foreignkey')
        except:
            pass
        try:
            batch_op.drop_constraint('fk_domicilios_departamento_id_departamentos', type_='foreignkey')
        except:
            pass
        try:
            batch_op.drop_constraint('fk_domicilios_municipio_id_municipios', type_='foreignkey')
        except:
            pass
        batch_op.create_foreign_key(batch_op.f('fk_domicilios_tipo_domicilio_id_tipos_domicilio'), 'tipos_domicilio', ['tipo_domicilio_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_domicilios_municipio_id_municipios'), 'municipios', ['municipio_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_domicilios_departamento_id_departamentos'), 'departamentos', ['departamento_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razon_social', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fecha_constitucion', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('clave_ingreso', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actividad_economica_id', sa.UUID(), nullable=True))
        batch_op.alter_column('nombre_comercial',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('regimen_fiscal_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('tipo_persona_id',
               existing_type=sa.UUID(),
               nullable=True)
        try:
            batch_op.drop_constraint('empresas_nit_key', type_='unique')
        except:
            pass
        batch_op.create_unique_constraint(batch_op.f('uq_empresas_nit'), ['nit'])
        try:
            batch_op.drop_constraint('fk_empresas_regimen_fiscal', type_='foreignkey')
        except:
            pass
        try:
            batch_op.drop_constraint('fk_empresas_tipo_persona', type_='foreignkey')
        except:
            pass
        batch_op.create_foreign_key(batch_op.f('fk_empresas_tipo_persona_id_tipos_persona'), 'tipos_persona', ['tipo_persona_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_empresas_actividad_economica_id_actividades_economicas_sat'), 'actividades_economicas_sat', ['actividad_economica_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_empresas_regimen_fiscal_id_regimenes_fiscales'), 'regimenes_fiscales', ['regimen_fiscal_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_empresas_regimen_fiscal_id_regimenes_fiscales'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_empresas_actividad_economica_id_actividades_economicas_sat'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_empresas_tipo_persona_id_tipos_persona'), type_='foreignkey')
        batch_op.create_foreign_key('fk_empresas_tipo_persona', 'tipos_persona', ['tipo_persona_id'], ['id'])
        batch_op.create_foreign_key('fk_empresas_regimen_fiscal', 'regimenes_fiscales', ['regimen_fiscal_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_empresas_nit'), type_='unique')
        batch_op.create_unique_constraint('empresas_nit_key', ['nit'])
        batch_op.alter_column('tipo_persona_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('regimen_fiscal_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('nombre_comercial',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('actividad_economica_id')
        batch_op.drop_column('clave_ingreso')
        batch_op.drop_column('fecha_constitucion')
        batch_op.drop_column('razon_social')

    with op.batch_alter_table('domicilios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_domicilios_departamento_id_departamentos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_domicilios_municipio_id_municipios'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_domicilios_tipo_domicilio_id_tipos_domicilio'), type_='foreignkey')
        batch_op.create_foreign_key('fk_domicilios_municipio_id_municipios', 'municipios', ['municipio_id'], ['id'])
        batch_op.create_foreign_key('fk_domicilios_departamento_id_departamentos', 'departamentos', ['departamento_id'], ['id'])
        batch_op.create_foreign_key('fk_domicilios_tipo_domicilio_id_tipos_domicilio', 'tipos_domicilio', ['tipo_domicilio_id'], ['id'])

    # ### end Alembic commands ###
