"""add: libros compras y ventas sat

Revision ID: 21055b1fcffc
Revises: ba7325eae3fc
Create Date: 2026-05-27 10:36:01.461890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision: str = '21055b1fcffc'
down_revision: Union[str, None] = 'ba7325eae3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    schema_actual = os.environ.get("TENANT_SCHEMA", "public")
    if schema_actual == 'system':
        return
    idx_catalogo_viejo = f"ix_{schema_actual}_impuestos_catalogo"
    idx_factura_viejo = f"ix_{schema_actual}_impuestos_factura"
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sat_libros',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo_libro', sa.Enum('COMPRAS', 'VENTAS', name='tipolibro', native_enum=False), nullable=False),
    sa.Column('regimen_fiscal', sa.Enum('NORMAL', 'PEQUENO_CONTRIBUYENTE', name='regimenfiscal', native_enum=False), nullable=False),
    sa.Column('anio_periodo', sa.SmallInteger(), nullable=False),
    sa.Column('mes_periodo', sa.SmallInteger(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'FINALIZADO', 'PRESENTADO', name='estadolibro', native_enum=False), server_default='borrador', nullable=False),
    sa.Column('total_lineas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_base_imponible', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_monto', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('finalizado_por', sa.UUID(), nullable=True),
    sa.Column('finalizado_el', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_el', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mes_periodo BETWEEN 1 AND 12', name='chk_sat_libros_mes_periodo'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo_libro', 'anio_periodo', 'mes_periodo', name='uq_sat_libros_periodo')
    )
    with op.batch_alter_table('sat_libros', schema=None) as batch_op:
        batch_op.create_index('idx_sat_libros_empresa_periodo', ['empresa_id', 'anio_periodo', 'mes_periodo'], unique=False)

    op.create_table('sat_libros_lineas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('libro_id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('numero_secuencia', sa.Integer(), nullable=False),
    sa.Column('fecha_documento', sa.Date(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('es_exento', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('es_exonerado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('base_imponible', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('monto_iva', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('credito_fiscal', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('debito_fiscal', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['sat_libros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libro_id', 'numero_secuencia', name='uq_sat_libros_lineas_secuencia')
    )
    with op.batch_alter_table('sat_libros_lineas', schema=None) as batch_op:
        batch_op.create_index('idx_sat_libros_lineas_libro', ['libro_id'], unique=False)

    with op.batch_alter_table('facturas_electronicas', schema=None) as batch_op:
        try:
            batch_op.drop_index('idx_facturas_xml_filename')
        except:
            pass
        try:
            batch_op.drop_index(batch_op.f('ix_facturas_electronicas_moneda_id'))
        except:
            pass
        batch_op.create_index(batch_op.f('ix_facturas_electronicas_moneda_id'), ['moneda_id'], unique=False)
        try:
            batch_op.drop_index(batch_op.f('ix_facturas_electronicas_tipo_documento_id'))
        except:
            pass
        batch_op.create_index(batch_op.f('ix_facturas_electronicas_tipo_documento_id'), ['tipo_documento_id'], unique=False)
        batch_op.drop_constraint('fk_facturas_catalogo_monedas', type_='foreignkey')
        batch_op.drop_constraint('fk_facturas_tipos_dte', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_dte', ['tipo_documento_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'catalogo_monedas', ['moneda_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('facturas_impuestos_especiales', schema=None) as batch_op:
        batch_op.drop_index(idx_catalogo_viejo)
        batch_op.drop_index(idx_factura_viejo)
        batch_op.create_index(batch_op.f('ix_facturas_impuestos_especiales_catalogo_id'), ['catalogo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_impuestos_especiales_factura_id'), ['factura_id'], unique=False)
        batch_op.drop_constraint('facturas_impuestos_especiales_catalogo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'catalogo_impuestos_especiales', ['catalogo_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_constraint('partidas_numero_poliza_empresa_unique', type_='unique')

    with op.batch_alter_table('plan_cuentas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_cuentas_codigo'), ['codigo'], unique=False)

    with op.batch_alter_table('secuencias', schema=None) as batch_op:
        batch_op.drop_constraint('secuencias_entidad_empresa_id_key', type_='unique')
        batch_op.create_unique_constraint('uq_secuencias_entidad_empresa', ['entidad', 'empresa_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    schema_actual = os.environ.get("TENANT_SCHEMA", "public")
    if schema_actual == 'system':
        return
    idx_catalogo_viejo = f"ix_{schema_actual}_impuestos_catalogo"
    idx_factura_viejo = f"ix_{schema_actual}_impuestos_factura"
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secuencias', schema=None) as batch_op:
        batch_op.drop_constraint('uq_secuencias_entidad_empresa', type_='unique')
        batch_op.create_unique_constraint('secuencias_entidad_empresa_id_key', ['entidad', 'empresa_id'])

    with op.batch_alter_table('plan_cuentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_cuentas_codigo'))

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.create_unique_constraint('partidas_numero_poliza_empresa_unique', ['numero_poliza', 'empresa_id'])

    with op.batch_alter_table('facturas_impuestos_especiales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('facturas_impuestos_especiales_catalogo_id_fkey', 'catalogo_impuestos_especiales', ['catalogo_id'], ['id'])
        try:
            batch_op.drop_index(idx_factura_viejo)
        except:
            pass
        try:
            batch_op.drop_index(idx_catalogo_viejo)
        except:
            pass
        batch_op.create_index(idx_factura_viejo, ['factura_id'], unique=False)
        batch_op.create_index(idx_catalogo_viejo, ['catalogo_id'], unique=False)

    with op.batch_alter_table('facturas_electronicas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_facturas_tipos_dte', 'tipos_dte', ['tipo_documento_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_facturas_catalogo_monedas', 'catalogo_monedas', ['moneda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('ix_facturas_electronicas_tipo_documento_id')
        batch_op.drop_index('ix_facturas_electronicas_moneda_id')
        batch_op.create_index('idx_facturas_xml_filename', ['xml_filename'], unique=False)

    with op.batch_alter_table('sat_libros_lineas', schema=None) as batch_op:
        batch_op.drop_index('idx_sat_libros_lineas_libro')

    op.drop_table('sat_libros_lineas')
    with op.batch_alter_table('sat_libros', schema=None) as batch_op:
        batch_op.drop_index('idx_sat_libros_empresa_periodo')

    op.drop_table('sat_libros')
    # ### end Alembic commands ###
