"""add: total_exento a SatLibro

Revision ID: 69d681675d93
Revises: 04e2a9159633
Create Date: 2026-05-27 13:21:39.626336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d681675d93'
down_revision: Union[str, None] = '04e2a9159633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat_libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_exento', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat_libros', schema=None) as batch_op:
        batch_op.drop_column('total_exento')

       # ### end Alembic commands ###
