"""add cierre configuracion cierre empresa

Revision ID: 7660b41a3d2
Revises: 773aab3dc84c
Create Date: 2026-06-09 00:00:00.000000
"""
import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7660b41a3d2'
down_revision = '773aab3dc84c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    schema_actual = os.environ.get("TENANT_SCHEMA", "public")
    if schema_actual == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Agregar las columnas
    op.add_column(
        'empresas', 
        sa.Column('cuenta_utilidad_periodo_id', postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.add_column(
        'empresas', 
        sa.Column('cuenta_utilidades_acumuladas_id', postgresql.UUID(as_uuid=True), nullable=True)
    )
    
    # 2. Crear las restricciones de clave foránea
    op.create_foreign_key(
        'fk_empresa_cuenta_utilidad_periodo', 
        'empresas', 'plan_cuentas', 
        ['cuenta_utilidad_periodo_id'], ['id']
    )
    op.create_foreign_key(
        'fk_empresa_cuenta_utilidades_acumuladas', 
        'empresas', 'plan_cuentas', 
        ['cuenta_utilidades_acumuladas_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    schema_actual = os.environ.get("TENANT_SCHEMA", "public")
    if schema_actual == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Eliminar las restricciones de clave foránea primero
    op.drop_constraint('fk_empresa_cuenta_utilidades_acumuladas', 'empresas', type_='foreignkey')
    op.drop_constraint('fk_empresa_cuenta_utilidad_periodo', 'empresas', type_='foreignkey')
    
    # 2. Eliminar las columnas
    op.drop_column('empresas', 'cuenta_utilidades_acumuladas_id')
    op.drop_column('empresas', 'cuenta_utilidad_periodo_id')
    # ### end Alembic commands ###