"""chg: migrar libros sat a public

Revision ID: 9e09153f8cc1
Revises: fe437fb194e1
Create Date: 2026-05-27 17:05:12.172522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import os

# revision identifiers, used by Alembic.
revision: str = '9e09153f8cc1'
down_revision: Union[str, None] = 'fe437fb194e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    tenant_schema = os.environ.get("TENANT_SCHEMA", "public")
    if tenant_schema == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_electronicas', schema=None) as batch_op:
        batch_op.drop_constraint('facturas_electronicas_moneda_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('facturas_electronicas_tipo_documento_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_dte', ['tipo_documento_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'catalogo_monedas', ['moneda_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('facturas_impuestos_especiales', schema=None) as batch_op:
        batch_op.drop_constraint('facturas_impuestos_especiales_catalogo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'catalogo_impuestos_especiales', ['catalogo_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('sat_libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_libro_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('regimen_fiscal_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('estado_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('uq_sat_libros_periodo', type_='unique')
        batch_op.create_unique_constraint('uq_sat_libros_periodo', ['empresa_id', 'tipo_libro_id', 'regimen_fiscal_id', 'anio_periodo', 'mes_periodo'])
        batch_op.create_foreign_key(None, 'regimenes_fiscales', ['regimen_fiscal_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'tipos_libro', ['tipo_libro_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'estados_libro', ['estado_id'], ['id'], referent_schema='public')
        batch_op.drop_column('tipo_libro')
        batch_op.drop_column('estado')
        batch_op.drop_column('regimen_fiscal')

    # ### end Alembic commands ###


def downgrade() -> None:
    tenant_schema = os.environ.get("TENANT_SCHEMA", "public")
    if tenant_schema == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sat_libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regimen_fiscal', sa.VARCHAR(length=21), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=10), server_default=sa.text("'borrador'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo_libro', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_sat_libros_periodo', type_='unique')
        batch_op.create_unique_constraint('uq_sat_libros_periodo', ['empresa_id', 'tipo_libro', 'anio_periodo', 'mes_periodo'])
        batch_op.drop_column('estado_id')
        batch_op.drop_column('regimen_fiscal_id')
        batch_op.drop_column('tipo_libro_id')

    with op.batch_alter_table('facturas_impuestos_especiales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('facturas_impuestos_especiales_catalogo_id_fkey', 'catalogo_impuestos_especiales', ['catalogo_id'], ['id'])

    with op.batch_alter_table('facturas_electronicas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('facturas_electronicas_tipo_documento_id_fkey', 'tipos_dte', ['tipo_documento_id'], ['id'])
        batch_op.create_foreign_key('facturas_electronicas_moneda_id_fkey', 'catalogo_monedas', ['moneda_id'], ['id'])

    # ### end Alembic commands ###
