"""add: total_exento a Factura Electrónica

Revision ID: fe437fb194e1
Revises: 69d681675d93
Create Date: 2026-05-27 13:29:11.456424

"""
import os
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fe437fb194e1'
down_revision: Union[str, None] = '69d681675d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    tenant_schema = os.environ.get("TENANT_SCHEMA", "public")
    if tenant_schema == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_electronicas', schema=None) as batch_op:
        batch_op.drop_constraint('facturas_electronicas_moneda_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('facturas_electronicas_tipo_documento_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_dte', ['tipo_documento_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'catalogo_monedas', ['moneda_id'], ['id'], referent_schema='public')
        # batch_op.add_column(sa.Column('total_exento', sa.Numeric(15, 2), server_default='0.00', nullable=False))

    with op.batch_alter_table('facturas_impuestos_especiales', schema=None) as batch_op:
        batch_op.drop_constraint('facturas_impuestos_especiales_catalogo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'catalogo_impuestos_especiales', ['catalogo_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    tenant_schema = os.environ.get("TENANT_SCHEMA", "public")
    if tenant_schema == 'system':
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_impuestos_especiales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('facturas_impuestos_especiales_catalogo_id_fkey', 'catalogo_impuestos_especiales', ['catalogo_id'], ['id'])

    with op.batch_alter_table('facturas_electronicas', schema=None) as batch_op:
        #   batch_op.drop_column("total_exento")
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('facturas_electronicas_tipo_documento_id_fkey', 'tipos_dte', ['tipo_documento_id'], ['id'])
        batch_op.create_foreign_key('facturas_electronicas_moneda_id_fkey', 'catalogo_monedas', ['moneda_id'], ['id'])

    # ### end Alembic commands ###
