"""add: normalizacion para perfil de Empresas

Revision ID: 6f5d6816d7c8
Revises: 50e509a94018
Create Date: 2026-05-27 20:54:58.826787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f5d6816d7c8'
down_revision: Union[str, None] = '50e509a94018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_iso', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tipos_domicilio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='public'
    )
    op.create_table('tipos_persona',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('municipios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['public.departamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('regimen_dte_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regimen_id', sa.UUID(), nullable=False),
    sa.Column('dte_id', sa.UUID(), nullable=False),
    sa.Column('es_exclusivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dte_id'], ['public.tipos_dte.id'], ),
    sa.ForeignKeyConstraint(['regimen_id'], ['public.regimenes_fiscales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.add_column('catalogo_impuestos_especiales', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('catalogo_impuestos_especiales', 'created_at')
    op.drop_constraint('users_tenant_id_fkey1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey1', 'users', 'tenants', ['tenant_id'], ['id'])
    op.add_column('catalogo_impuestos_especiales', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('catalogo_impuestos_especiales', 'creado_en')
    op.drop_table('regimen_dte_config', schema='public')
    op.drop_table('municipios', schema='public')
    op.drop_table('tipos_persona', schema='public')
    op.drop_table('tipos_domicilio', schema='public')
    op.drop_table('departamentos', schema='public')
    # ### end Alembic commands ###
