"""add: codigo_iso a municipios

Revision ID: d5adf1401176
Revises: 6f5d6816d7c8
Create Date: 2026-05-28 12:27:32.094446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5adf1401176'
down_revision: Union[str, None] = '6f5d6816d7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipios', sa.Column('codigo_iso', sa.String(length=4), nullable=False))
    op.drop_constraint('fk_municipios_departamento_id_departamentos', 'municipios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_municipios_departamento_id_departamentos'), 'municipios', 'departamentos', ['departamento_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_municipios_departamento_id_departamentos'), 'municipios', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_municipios_departamento_id_departamentos', 'municipios', 'departamentos', ['departamento_id'], ['id'])
    op.drop_column('municipios', 'codigo_iso')
    # ### end Alembic commands ###
