"""add: actividad economica sat

Revision ID: d7de768ad222
Revises: 6d0326e3176f
Create Date: 2026-05-28 13:28:15.139598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7de768ad222'
down_revision: Union[str, None] = '6d0326e3176f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_economicas_sat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_sat', sa.String(length=20), nullable=False),
    sa.Column('nombre_actividad', sa.String(length=255), nullable=False),
    sa.Column('seccion', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actividades_economicas_sat')),
    schema='public'
    )
    op.create_index(op.f('ix_public_actividades_economicas_sat_codigo_sat'), 'actividades_economicas_sat', ['codigo_sat'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_actividades_economicas_sat_codigo_sat'), table_name='actividades_economicas_sat', schema='public')
    op.drop_table('actividades_economicas_sat', schema='public')
    # ### end Alembic commands ###
