"""add: perfil_tenant_usuarios

Revision ID: db7f08b62617
Revises: d7de768ad222
Create Date: 2026-05-29 07:50:01.367394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7f08b62617'
down_revision: Union[str, None] = 'd7de768ad222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('admin_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('max_usuarios', sa.Integer(), default=3, nullable=True))
    op.drop_constraint('tenants_schema_name_key', 'tenants', type_='unique')
    op.create_unique_constraint(op.f('uq_tenants_schema_name'), 'tenants', ['schema_name'], schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_tenant_id_tenants'), 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('uq_tenants_schema_name'), 'tenants', schema='public', type_='unique')
    op.create_unique_constraint('tenants_schema_name_key', 'tenants', ['schema_name'])
    op.drop_column('tenants', 'max_usuarios')
    op.drop_column('tenants', 'admin_email')
    # ### end Alembic commands ###
